riga/law

examples/htcondor_at_vispa/README.md, examples/htcondor_at_vispa/analysis/framework.py
Python 3 will fail due to a wrong keyword argument.
=> Fix typo in VISPA example

examples/loremipsum/setup.sh
Shallow clones of the software in the examples should be made to reduce their size.
=> Make shallow clones of the software in the loremipsum example.

law/contrib/arc/job.py, law/contrib/glite/job.py, law/contrib/htcondor/job.py, law/contrib/lsf/job.py, law/job/base.py, law/util.py, law/workflow/base.py, law/workflow/remote.py
A few minor fixes to make the VISPA example work together with Python 3.
Main changes:
- Replace `sys.maxint` with `sys.maxsize` since it was removed in Python 3
- Fix `utils.flatten` since `OrderedDict.values()` now returns a `ValuesView` instead of a `list`
- Convert `input_files` to list
- Explicitly handle bytes in `encode_list`
=> Improve Python 3 compatibility

law/cli/cli.py
This prevents errors if a user runs the law CLI on Python 3 without a command.
```bash
> law
Traceback (most recent call last):
File "/home/lgeiger/miniconda3/bin/law", line 11, in <module>
load_entry_point('law', 'console_scripts', 'law')()
File "/home/lgeiger/law/law/cli/cli.py", line 34, in run
mods[args.command].execute(args)
KeyError: None
```
```bash
> law
usage: law [-h] {run,db,config,software,completion} ...
law command line tool
positional arguments:
{run,db,config,software,completion}
subcommands
optional arguments:
-h, --help            show this help message and exit
```
=> Show help message if law CLI executes without command

law/target/formatter.py
`json.dump` and `json.load` allow to use a custom [Encoder/Decoder via the `cls` keyword argument](https://docs.python.org/3/library/json.html#json.dump).
Unfortunately this conflicts with the PEP8 naming convention of class methods resulting in a type error: `TypeError: dump() got multiple values for argument 'cls'`.
This PR renames `cls` to `cls_` for the affected class methods.
=> JSONFormatter: Rename cls argument to allow for custom Encoder

law/task/base.py
[`luigi` treats tasks without a `run` method as external Tasks](https://github.com/spotify/luigi/blob/636a0203f650688c4ce249a994c1d6169e5a16af/luigi/worker.py#L85) and therefor won't run them if dependencies are missing.
This PR fixes the implementation of `WrapperTask` to match `luigi`: see [`luigi.WrapperTask`](https://github.com/spotify/luigi/blob/master/luigi/task.py#L800) and [`luigi.Task::run()`](https://github.com/spotify/luigi/blob/master/luigi/task.py#L636).
I also added the `ExternalTask` class the [same way as defined in luigi](https://github.com/spotify/luigi/blob/master/luigi/task.py#L726) and modified `law.cli.db` to include external tasks in the completions.
=> Fix implementation of WrapperTask and ExternalTask

docs/contrib/hdf5.rst, docs/contrib/index.rst, law/contrib/hdf5/__init__.py, law/contrib/hdf5/formatter.py
This adds a HDF5 Formatter using [`h5py`](https://github.com/h5py/h5py).
I added this functionality to `law.contrib.hdf5` instead of `law.contrib.h5py` in order to make it easy to add support for HDF5 using [`pytable`](https://github.com/PyTables/PyTables) in the future.
=> Add HDF5 Formatter

law/contrib/slack/parameter.py, law/decorator.py, law/parameter.py
* The Slack API call is now started as a thread, such that is does not block task execution.
* The notification style is improved by utilising the attachment function of the Slack API.
=> Refactor Slack notifications to be asynchronous and pretty

law/workflow/base.py
Tolerance should not be considered when determining if a task is complete (threshold).
Also the docs of the threshold function were inconsistent, which is now fixed.
=> Remove tolerance from threshold computation

law/workflow/remote.py
Currently the loop over the waiting jobs in the `submit` function of the `BaseRemoteWorkflowProxy` breaks when `n_parallel` jobs are reached. This is fine for the sole purpose of determining which tasks need to be submitted.
However, if the waiting list contains multiple sequences of unfinished and already finished jobs it will break during an sequence of unfinished jobs, when `n_parallel` is exceeded, and leave the remaining already finished jobs in a later section of the waiting list uncounted. This results in the finished jobs count being lower that it actually is in the polling. The missing finished jobs will eventually be included without being resubmitted, so this is a purely cosmetical, albeit very confusing issue.
The proposed solution keeps scanning the waiting list for the sole …
=> Continue scanning and pruning the whole waiting list list when submitting

law/decorator.py
The timeit decorator can wrap a bound method of a task and log its 
execution time in a human readable format
=> [law] decorator: added timeit decorator

law/contrib/git/__init__.py, law/contrib/git/scripts/bundle_repository.sh, law/contrib/mercurial/__init__.py, law/contrib/mercurial/scripts/bundle_repository.sh
The bundling of submodules did not take into account changes and was using git features that might not exist on versions older than 3 years. The bundling strategy now uses `git ls-files` followed by a simple `tar -cz` instead of `git archive`.
This fixes #72.
=> [contrib/git] Fix bundling of git submodules.

law/config.py, law/contrib/docker/sandbox.py, law/contrib/singularity/sandbox.py
This PR adds the option to run singularity sandboxes without bind access and/or without forwarding the law environment.
Some singularity instances disallow user bind control, which clashes with the current directory forwarding.
For the base law environment (law & dependencies, config, cli), one could instead point to the paths on the host system (if they are accessible from within the container). This would mean that the PYTHONPATH includes the entire site/dist-packages directory instead of only the law dependencies. The required packages could also be copied to a tmp directory on the host system to prevent this.
As an alternative, one could not forward the base environment and set up an independent environment in the sandbox, e.g. using sandbox_setup_cmds(). I think this also makes sense …
=> Singularity sandboxes without bind access

law/contrib/htcondor/job.py
condor_history scans per default the complete history. The option ` -limit`  stops `condor_history` after it founds the given number.
This reduces the time to check the status of old jobs.
=> Add option -limit to condor_history

README.rst, law/cli/completion.sh, law/cli/index.py, law/cli/run.py, law/contrib/cms/job.py, law/polyfills.sh, law/task/base.py
This PR fixes the autocompletion in cases where the task family contains underscores. Also, when running `law index`, errors are logged in case a task family contains dashes (probably in the namespace definition), or underscores in the class name (leads to ambiguities between task families and task-level parameters, and is considered bad Python practice anyway).
=> Fix autocompletion

law/contrib/arc/workflow.py, law/contrib/glite/job.py, law/contrib/glite/workflow.py, law/contrib/htcondor/job.py, law/contrib/htcondor/workflow.py, law/contrib/lsf/job.py, law/contrib/lsf/workflow.py, law/workflow/base.py, law/workflow/remote.py
This PR changes two aspects regarding the interaction with jobs:
1. Remote workflows had to implement their own `submit_jobs()` method, but they were all very similar. A generic method is now provided directly by the `RemoteWorkflowProxy` base class.
2. Except for submission, no (keyword) arguments were passed to methods of `JobManager` implementations such as `cancel()` and `query()`. Now, there is a way to define kwargs to pass to those methods directly on task level.
=> Refactor job argument handling

docs/contrib/tensorflow.rst, law/contrib/tensorflow/__init__.py, law/contrib/tensorflow/formatter.py
This PR renames the `TFConstantGraphFormatter` to `TFGraphFormatter` and also changes its formatter name to `tf_graph`. Whether or not variables are converted to constants is an optional feature now. Also, the `dump()` method accepts polymorphic and concrete (autograph) functions now and extracts their graph.
=> Refactor TF graph formatter for v2, rename it

law/patches.py
Hi,
This PR fixes a "RuntimeError: maximum recursion depth exceeded while calling a Python object". `_add` called itself forever...
Best, Peter
=> Fix: RuntimeError: maximum recursion depth exceeded

law/contrib/htcondor/job.py
Hi,
I wanted to look at LAW's htcondor implementation, so I cloned it and open the `htcondor/job.py` in emacs and pylint gave me a bunch of warnings. The one that I fixed here was that the parameter `job_ids` was used at no point in the `parse_long_output` method, so I removed it to avoid confusion.
The other warnings were mostly the [no-else-return](https://pheanex.github.io/pylint/) warning by pylint because of the unnecessary use of `else` after `if...return`, but I think that is a question of style, e.g. kubernetes also use this under the name *space shuttle style*.
By the way, unrelated to the PR, I was looking at LAW's htcondor implementation because I was curious how it compares to the [htcondor implementation](https://github.com/nils-braun/b2luigi/blob/main/b2luigi/batch/processes/ …
=> Remove unused parameter job_ids

law/target/formatter.py
switching from `load` to `safe_load` avoids this warning to be printed, and the possibility of unsafe behavior:
```
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read
https://msg.pyyaml.org/load for full details.
```
=> switch so safe loading of yaml files

law/contrib/rich/logger.py
Hi @riga,
this PR allows to pass kwargs down to the RichHandler.
This is useful to e.g. disable time in logging by adding `show_time=False`.
By default this is set to `True` and creates a rather ugly indentation:
However there are also other useful options, such as `rich_tracebacks`, which can be passed then to the RichHandler:
Example usage:
```python
import law
law.contrib.load("rich")
law.rich.replace_console_handlers(show_time=False, rich_tracebacks=True)
```
Best, Peter
=> [rich] allow passing through kwargs to RichHandler

law/contrib/rich/logger.py
[_the following only affects logging using `contrib.rich`_]
Hi @riga,
`rich` automatically adds (rather intelligent) coloring. Currently is clashes with `law`'s own coloring in case `str(task)` or `repr(task)` is called and their coloring option is set to `True`. 
This leads to malformed output strings such as: 
```shell
...[0;49;32mGroupCoffeaProcessesWithModel[0m([1;49;34mversion[0m=prod27, [1;49;34mnotify[0m=False, [1;49;34manalysis_choice[0m=bbww_sl, [1;49;34myear[0m=2017, [1;49;34mrecipe[0m=tth,...
```
It seems that by default it only affects `str(task)` in the following output:
```shell
[pid 60651] Worker Worker(salt=809229854, workers=1, host=..., username=..., pid=60651) running <str(task)>
```
(Seems that this here is the bad boy initially: …
=> [rich] set colored_[repr/str] options in config to False

law.cfg.example, law/config.py, law/target/file.py, law/target/local.py
Hi @riga ,
This small PR adds the possibility to display the file size for any `FileSystemTarget`-type target class.
This looks as follows:
```python
In [1]: import law
In [2]: f = law.LocalFileTarget("MANIFEST.in")
In [3]: f.__repr__()
Out[3]: 'LocalFileTarget(path=/Users/peter/repos/law/MANIFEST.in)'
In [4]: law.Config.instance().set("target", "filesize_repr", "True")
In [5]: f.__repr__()
Out[5]: 'LocalFileTarget(path=/Users/peter/repos/law/MANIFEST.in, 156.0 bytes)'
```
This is not (yet) implemented for collections as this might be expensive information to collect, especially for _many_ remote targets.
Best, Peter
=> [target] add optional file size information to representation

README.rst
The current URL fails to load for me (Ubuntu LTS, Firefox latest, NZ). Cheers
=> Fix GFAL2 URL

law/contrib/slurm/job.py
When a slurm job is cancelled out of Law's control and while Law is not
actively polling it, Law still thinks it is running. On the first poll, it will
then normally find out that the job has failed and restart it.
However, the slurm scheduler forgets about old jobs after some time. Trying to
query the status of such a job returns an error. Handle this by returning a
FAILED status for all jobs when squeue fails with "Invalid job id specified".
=> Fix querying slurm jobs after they're gone

law/decorator.py
Caught this typo that was interfering with `ForestMerge` tasks running locally.
=> Fix typo in 'localize' decorator.

law/contrib/tasks/__init__.py, law/task/base.py, law/workflow/base.py
This PR enables the forwarding of cached objects (mainly a reference to the workflow task instance) from workflows to their branches, as well as across branches. This results in a significant speedup during instantiation and branch map creation of rather complex workflows.
Closes #138.
=> Forward cache workflow between branches.

docker/Dockerfile_centos7_py38
Hi!
The Dockerfile placed at "docker/Dockerfile_centos7_py38" contains the best practice violation [DL3048](https://github.com/hadolint/hadolint/wiki/DL3048) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3048 occurs when the pattern used for the label keys does not match the format recommended by official guidelines.
In this pull request, we propose a fix for that smell generated by our fixing tool. We manually checked that the patch is correct before opening the pull request.
To fix this smell, specifically, the label keys are refactored to match the correct format.
This change is only aimed at fixing that specific smell. In the case the fix is not valid or useful, please briefly indicate the reason along with suggestions for possible improvements. …
=> Fix for Dockerfile smell DL3048

law/task/base.py, law/workflow/base.py
This PR changes the way the `--workflow TYPE` parameter is passed between (workflow) tasks.
Considering the following scenario,
```mermaid
graph TD
A("TaskA (HTCondorWorkflow, LocalWorkflow)")
B("TaskB (LocalWorkflow)")
C("TaskC (HTCondorWorkflow, LocalWorkflow)")
A --> B
B --> C
```
running `law run TaskC --workflow htcondor` will currently
- (correctly) trigger TaskC to run on htcondor, before that
- (correctly) trigger TaskB to run locally, and before that
- (incorrectly?) trigger TaskA to run locally as well.
Generally one would want to run **TaskA on htcondor as well**, but since TaskB is not able to do so, it will pass it's own workflow type, `"local"`, upstream to TaskA.
In the current state, this could be avoided by configuring the requirements from TaskB to TaskA in a way that …
=> Passthrough workflow type.

law/workflow/base.py
Class instance `self` was given as positional argument although `req_workflow` is a class method with native access to `self`. This wasn't a problem with the previous implementation using `req` directly without the new helper method `req_workflow` introduced in commit https://github.com/riga/law/commit/7d4f6793baff103cd69bf6c88ac446ffb37a3402#diff-797a1ce240571ca7714bd6fb314f3eaa3e1e241982c9a8ee48cdfbf6e4c72394L1025-R1056.
=> Fix TypeError causing function call

.github/workflows/lint_and_test.yml, .github/workflows/publish_pypi.yml, docs/api/cli/index.rst, docs/api/cli/luigid.rst, docs/api/cli/quickstart.rst, law.cfg.example, law/cli/cli.py, law/cli/completion.sh, law/cli/luigid.py, law/cli/run.py, law/contrib/cms/crab/crab_wrapper.sh, law/contrib/cms/job.py, law/contrib/cms/workflow.py, law/contrib/htcondor/config.py, law/contrib/htcondor/htcondor_wrapper.sh, law/contrib/htcondor/job.py, law/contrib/htcondor/workflow.py, law/job/base.py, law/job/law_job.sh, law/target/collection.py, law/task/base.py, law/workflow/base.py, law/workflow/remote.py
This PR mainly contains the group submission of htcondor jobs (detailed below). However, there are two smaller features that coming with this PR:
1. `law luigid` sub command: The law configuration file can contain sections that synced with the internal luigi config (via naming sections `[luigi_<section>]`), which is a convenience to just maintain a single file. However, when starting the central scheduler with `luigid`, these sections are not considered. The new `law luigid` sub command loads and synchronizes the config and then starts the central scheduler, just like plain `luigid` would do.
2. Interface to declare job resource as luigi's `process_resources` in remote workflows: Remote workflows like `HTCondorWorkflow` can now declare the resources that their jobs claim to the central …
=> Add htcondor group submission.

law.cfg.example, law/contrib/arc/workflow.py, law/contrib/cms/workflow.py, law/contrib/glite/workflow.py, law/contrib/htcondor/workflow.py, law/contrib/lsf/workflow.py, law/contrib/slurm/workflow.py, law/job/base.py
=> Allow job_file_dir_mkdtmp to be path patterns.

law/contrib/singularity/sandbox.py
The [`forward_law`](https://github.com/riga/law/blob/master/law/contrib/singularity/sandbox.py#L182) variable was getting parsed as a string instead of boolean leading to [this check](https://github.com/riga/law/blob/master/law/contrib/singularity/sandbox.py#L190) failing
=> Parse `forward_law` as bool in `Singularity.Sandbox`

law/contrib/pandas/__init__.py, law/contrib/pandas/formatter.py
These changes add the pandas `contrib` module.
For now this `contrib` module includes the `DataFrameFormatter`.
The `DataFrameFormatter` can be used to read and write instances of `pandas.DataFrame`.
=> Adds pandas `contrib` module

law/target/collection.py
In my tests, this gives a speed-up of a factor of more than 60 for a nested sibling file collection of 4000 files.
```console
$ python test.py
NestedSiblingFileCollection(len=4000, threshold=1.0, collections=4)
True
Total: 62.249094 seconds
$ python test.py
NestedSiblingFileCollection(len=4000, threshold=1.0, collections=4)
True
Total: 0.858903 seconds
```
Testing script:
```python
import law
from law import NestedSiblingFileCollection
import time
law.contrib.load("wlcg")
targets = []
for j in range(4):
for i in range(1000):
i += j*1000
targets.append(law.wlcg.WLCGFileTarget(f"HerwigRun/Dijets_LO/NPoff/{j}/Dijets_LOjob{i}.tar.bz2"))
collection = NestedSiblingFileCollection(targets)
print(collection)
start = time.time()
print(collection.complete())
end = time.time()
print(f"Total: …
```
=> Speedup NestedSiblinFileCollection when possible

law/contrib/root/formatter.py
Hi @riga , I found out that `ROOT.TFile` fails when opening files on the grid, but `ROOT.TFile.Open` doesn't. I've replaced it here, but I'm not sure it this change has any other implications.
=> Create TFile using Open instead of the TFile constructor
